### ISSUE TITLE
HDPVR2 Model

### ISSUE THREAD

**Issue by gsarrica** [jpoet/HauppaugeUSB#12]
Do all models of the HDPVR2 work with this? If so it may be nice to add it to the README.

My HDPRV 1 just died and I am looking for a replacement, however there are 3 versions of the hdpvr2 available on Hauppauge's site. 

Thank you.

**Comment by jpoet** [comment]
I know that all models of the Colossus2 work.  I personally only have the HD-PVR2 with the S/PDIF input, so that is what I test with.  It should work with most if not all models of the HD-PVR2, I just can guarantee it.

**Comment by stevenviola** [comment]
@gsarrica, I can confirm that models 157310 & 157320 of the PVR2 work with HauppaugeUSB. I've had mixed experience on Amazon ordering these, and sometimes received the Gaming Edition by mistake, but it'll still work. If you get one of the models I mentioned, you'll be able to use this application.

**Comment by gsarrica** [comment]
@jpoet Thank you for working on this. How do I donate?
