### ISSUE TITLE
Failed to open dev (v2)

### ISSUE THREAD

**Issue by neyuru** [jpoet/HauppaugeUSB#23]
As a non-root user I am unable to run hauppauge2. Double checked the serial number is correct and that I am in video group.

>/opt/Hauppauge/bin/hauppauge2 -s E585-00-00AF9EBE -R 7 -r 4000000 -d 1 -C 0 -p 4 -A 0 -o /tmp/testpipe_stream
>2020-06-05T17:03:00.261606 CRIT <main> Logger.cpp:83 (setLogLevelFilter) Changing loglevel to NOTC
>2020-06-05T17:03:00.261684 CRIT <main> hauppauge2.cpp:352 (main) Starting up
>Failed to open dev.
>2020-06-05T17:03:00.267399 CRIT <main> hauppauge2.cpp:360 (main) Device E585-00-00AF9EBE not found on USB bus.
>Failed to open dev.

**Comment by jpoet** [comment]
Did you skip the udev step in the instructions?

**Comment by neyuru** [comment]
Do you mean creating the nano /etc/udev/rules.d/99-Hauppauge.rules file? If so, no... =(

**Comment by neyuru** [comment]
btw, in that file there are:

>ATTRS{idVendor} ATTR{serial}

options. Are these correctly spelled? I mean one is ATTRS and the other is ATTR

**Comment by jhoyt4** [comment]
this are correct udev rule reads

# colossus2
SUBSYSTEMS=="usb",ATTRS{idVendor}=="2040",ATTR{serial}=="E585-00-00D642B7",MODE="0660",GROUP="video",SYMLINK+="colossus2-1",TAG+="systemd",RUN="/bin/sh -c 'echo -1 > /sys$devpath/power/autosuspend'"

**Comment by neyuru** [comment]
I have 

```
# Device 1
SUBSYSTEMS=="usb",ATTRS{idVendor}=="2040",ATTR{serial}=="E585-00-00AF9EBE",MODE="0660",GROUP="video",SYMLINK+="hdpvr2_1",TAG+="systemd",RUN="/bin/sh -c 'echo -1 > /sys$devpath/power/autosuspend'"

# Device 2
SUBSYSTEMS=="usb",ATTRS{idVendor}=="2040",ATTR{serial}=="E585-00-00AF9EBE",MODE="0660",GROUP="video",SYMLINK+="colossus2-1",TAG+="systemd",RUN="/bin/sh -c 'echo -1 > /sys$devpath/power/autosuspend'"
```

**Comment by jhoyt4** [comment]
Just a note - the new udev rules won't apply until you reboot or run 
`udevadm control --reload-rules && udevadm trigger`

**Comment by jpoet** [comment]
You have 2 devices? both a Colossus2 and a HD-PVR2? Each will have its own serial number, and you are using the same one for both devices.

**Comment by neyuru** [comment]
@jhoyt4 reloading the rules did it.
@jpoet you're absolutely right, I will comment out the HD-PVR2 as I only have the Colossus2

Thank you, all!
