### ISSUE TITLE
Not stopping when used as a pipe

### ISSUE THREAD

**Issue by emveepee** [jpoet/HauppaugeUSB#31]
I am using hauppauge2 to pipe to nextpvr but it looks like hauppauge2 doesn't support SIGPIPE so when the pipe is closed hauppauge2 is left running.  Adding SIGPIPE here https://github.com/jpoet/HauppaugeUSB/blob/master/hauppauge2.cpp#L53 and here  https://github.com/jpoet/HauppaugeUSB/blob/master/hauppauge2.cpp#L61  seems to get it working.

Does this seem like a valid solution?

**Comment by jpoet** [comment]
That seems reasonable and I will make that change.

Please note that I no longer use this code, though, so I am unable to test the change. If someone wants to take ownership of this project I will happily give them commit privileges.

**Comment by emveepee** [comment]
> That seems reasonable and I will make that change.
> 
> Please note that I no longer use this code, though, so I am unable to test the change. If someone wants to take ownership of this project I will happily give them commit privileges.

Thanks, I will see how this evolves with my use with NextPVR.  I see an increasing need HDMI from Android as opposed to traditional STB and the Hauappauge devices remain the only AC3 option.    

Do you know if video passthrough in possible in Linux from the HDPVR 2?  I can plug USB into Windows and that does initialize it, unplug and plug into Linux and the video stays on.
